---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install nginx
  ansible.builtin.apt:
    name: "{{ nginx_pkg }}"
    state: present

- name: Configure Nginx with Custom templete
  ansible.builtin.template:
    src: ~/Ansible_Projects/nginx_server/templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/nginx.conf.j2
  notify: Restart nginx

- name: Create a sym_link for nginx.conf.j2
  ansible.builtin.file:
    src: /etc/nginx/sites-available/nginx.conf.j2
    dest: /etc/nginx/sites-enabled/nginx.conf.j2
    state: link
  notify: Reload nginx

- name: Deploy Static Website
  ansible.builtin.copy:
    src: ~/Ansible_Projects/nginx_server/files/index.html
    dest: "{{ web_root }}/index.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0644

- name: Start Nginx and enable it on boot
  ansible.builtin.service:
    name: "{{ nginx_service }}"
    state: started
    enabled: yes
